- hosts: kali-host
  become: true
  gather_facts: false
  tasks:
    - ansible.builtin.user:
        name: kali-user
        groups: sudo
        append: true
        shell: /bin/bash
        create_home: true
        password: "$6$OtcqMID40HCPh8U7$wLC30ns6ZozkW1sZQouh6a6XesOy7nenCbV42PjqGGRWN7W16x7SdVG8qsHmCV1IWT7/8UaqpnSXoUhk4rmpp."

    - ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/99-crczp-guac.conf
        content: |
          PasswordAuthentication yes
          KbdInteractiveAuthentication yes
          UsePAM yes
        owner: root
        group: root
        mode: "0644"

    - ansible.builtin.service:
        name: ssh
        state: restarted
