- hosts: ubuntu-host
  become: true
  gather_facts: false
  tasks:
    - ansible.builtin.user:
        name: ubuntu-user
        groups: sudo
        append: true
        shell: /bin/bash
        create_home: true
        password: "$6$REPLACE_WITH_SHA512_HASH"

    - ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/99-crczp-guac.conf
        content: |
          PasswordAuthentication yes
          KbdInteractiveAuthentication yes
          UsePAM yes
        owner: root
        group: root
        mode: "0644"

    - ansible.builtin.service:
        name: ssh
        state: restarted
